config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'

  resources :clients
  resources :applicants do
    member do
      get 'view_resume'
      get 'resume'
    end
    collection do
      get "search"
    end
  end
  resources :resumes do
    collection do
      get "search"
    end
  end

  root to: "clients#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/applicant.rb
class Applicant
  include Mongoid::Document
	include Mongoid::Attributes::Dynamic
  include Mongoid::Timestamps
  include Mongoid::Search


  field :bm_id, type: String
  field :username, type: String
  field :firstName, type: String
  field :lastName, type: String
  field :email, type: String
  field :phone, type: String
  field :city, type: String
  field :region, type: String
  field :postalCode, type: String
  field :country, type: String
  field :currentPay, type: String
  field :currentayType, type: String
  field :taxID, type: String
  field :veteranStatus, type: String
  field :disabledStatus, type: String
  field :employmentType, type: String
  field :race, type: String
  field :status, type: String
  field :source, type: String
  field :gender, type: String
  field :visaStatus, type: String
  field :createUserID, type: String
  field :salutation, type: String
  field :workEmail, type: String
  field :primarySkills, type: String

  validates :firstName, presence: true
  # validates :firstName, uniqueness: true
  validates :bm_id, uniqueness: true

  has_one :resume, dependent: :destroy

  search_in :userName, :firstName, :email, :workEmail, :primarySkills, :lastName,
  :city, :region, :postalCode, :veteranStatus, :VisaStatus #, tags: :name, category: :name, info: %i[summary description]


  def self.import_bmdata_from_xml
    obj1 = Parsexml.new
    total_count, list = obj1.get_files("public", "applicants")
    STDOUT.puts "Processing #{total_count} applicants"
    list.each_with_index do |item, i|
      _id = item["iD"].try(:strip)
      STDOUT.print "#{i + 1}......."
      _params = item.delete_if {|k,v| k.match(/(iD|officeID|clientID|date|modifyUserID|employeeID)/i) }
      _params.merge!(bm_id: _id)
      #STDOUT.puts "......#{_params.inspect}"
      c = Applicant.new(_params)
      if c.save
        #STDOUT.print "Saved"
      else
        STDOUT.puts "Errors: .#{_id}..#{c.errors.full_messages.inspect}"
      end
    end
  end

  def resume_present?
    res = Resume.where(applicantID: bm_id).first
    res.present?
  end
end

app/controllers/applicants_controller.rb
class ApplicantsController < ApplicationController
  before_action :load_applicant, except: [:index, :new, :create, :search, :search_applicant, :resume]

  def index
    @applicants = Applicant.only(:bm_id, :firstName, :lastName, :email, :primarySkills).paginate(page: params[:page], per_page: 100)
  end

  def search
    if params[:term].present?
      str = params[:match].presence || "all"
      @applicants = Applicant.full_text_search("#{params[:term]}", match: str.to_sym).paginate(page: params[:page], per_page: 100)
       #.where(:email => /#{params[:term]}/i)
       respond_to do |format|
          format.js
          format.html
        end
    else
      @applicants = Applicant.none
    end
  end

  def new
    @applicant = Applicant.new
  end

  def create
    @applicant = Applicant.new(applicant_params)
    if @applicant.save
      redirect_to applicants_path
    else
      Rails.logger.debug "\n\n..ERROR...#{@applicant.errors.full_messages.inspect}....\n"
      redirect_to resume_path(params[:resume_id]), alert: "#{@applicant.errors.full_messages}"
    end
  end

  def edit
    @applicant = Applicant.find(params[:id])
  end

  def update
    if @applicant.update(applicant_params)
      redirect_to applicants_path
    else
      render action: :edit
    end
  end

  def show
  end

  def destroy
    @applicant.destroy
    redirect_to applicants_path
  end

  def view_resume
    Rails.logger.debug "\n\n....app...#{@applicant.inspect}......\n\n"
    res = Resume.where(applicant_id: @applicant.id).first
      Rails.logger.debug "\n\n....es...#{res.inspect}......\n\n"
    @resume = @applicant.resume
    Rails.logger.debug "\n\n....res...#{@resume.inspect}......\n\n"
  end

  def resume
    @resume = Resume.where(applicantID: params[:id]).first
    Rails.logger.debug "\n\n....222...#{@resume.inspect}......\n\n"
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "resume"   # Excluding ".pdf" extension.
      end
    end
  end

  private
  def load_applicant
    @applicant = Applicant.find(params[:id])
  end

  def applicant_params
    params.permit(:username, :firstName, :email, :bm_id, :phone, :state, :postalCode, :primarySkills)
  end

end

app/views/applicants/_list.html.haml
= page_entries_info @applicants
%table.table.table-hover#applicants.display
  %thead
    %tr
      - applicant_colmn_names.each do |colmn|
        %th= colmn.capitalize
      %th
  %tbody
    - @applicants.each do |c|
      %tr
        - applicant_colmn_names.each do |colmn|
          %td
            - if colmn == "primarySkills"
              %p{style: "font-size:12px;width:250px;", "data-toggle" => "tooltip", "title" => c.send(colmn)}
                = h truncate(c.send(colmn), length: 80)
            - else
              = c.send(colmn)
        %td
          = link_to "Resume", resume_applicant_path(c.bm_id, "pdf"), target: "_blank" if c.resume_present?
          =# link_to "View Resume", view_resume_applicant_path(c), remote: true
          &nbsp;|&nbsp;
          = link_to "Edit", edit_applicant_path(c)
          &nbsp;|&nbsp;
          = link_to "Remove", applicant_path(c), method: :delete, dailog: {confirm: "Are u sure?"}

= will_paginate @applicants

:javascript
  $(document).ready(function() {
    $('#applicants').DataTable({
      "paging": false,
      "ordering": false,
      "info": false
    });
  } );

app/views/applicants/_my_modal.html.haml
#myModal.modal.fade{:role => "dialog", :tabindex => "-1"}
  .modal-dialog{style: "background:#fff;padding: 40px;"}
    %div{style: "white-space: pre-wrap;"}
      = @resume.content.html_safe

app/views/applicants/index.html.haml
= page_entries_info @applicants
%table.table.table-hover#applicants.display
  %thead
    %tr
      - applicant_colmn_names.each do |colmn|
        %th= colmn
      %th
  %tbody
    - @applicants.each do |c|
      %tr
        - applicant_colmn_names.each do |colmn|
          %td
            - if colmn == "primarySkills"
              %p{style: "font-size:12px;width:250px;", "data-toggle" => "tooltip", "title" => c.send(colmn)}
                = h truncate(c.send(colmn), length: 80)
            - else
              = c.send(colmn)
        %td
          = link_to "Edit", edit_applicant_path(c)
          = link_to "Remove", applicant_path(c), method: :delete, data: { confirm: 'Are you sure?' }
%br
= will_paginate @applicants
%br
%br
= link_to "New", new_applicant_path

:javascript
  $(document).ready(function() {
    $('#applicants').DataTable({
      "paging": false,
      "ordering": false,
      "info": false
    });
  } );

app/views/applicants/resume.pdf.erb
<div style="white-space: pre-wrap;">
  <% if @resume.present? %>
    <%= @resume.content %>
  <% else %>  
    "Resume not found!"
  <% end %>
</div>

app/views/applicants/search.html.haml
.panel{:style => "margin-top:36px;margin-bottom:45px;"}
  .panel-heading{:style => "text-align:center;margin: -1px;color:white;background-color:#4B515D !important;"}
    %h4 Search Candidates


.container
  .row
    .col-xs-8.col-xs-offset-2
      = form_tag(search_applicants_path, method: :get, remote: true) do
        .input-group
          .input-group-btn.search-panel
            %button.btn.btn-primary.dropdown-toggle{"data-toggle" => "dropdown", :type => "button"}
              %span#search_concept Filter by
              %span.caret
            %ul.dropdown-menu{:role => "menu"}
              %li
                %a{:href => "#all"} AND
              %li
                %a{:href => "#any"} OR
          %input#match{:name => "match", :type => "hidden", :value => "all"}
            %input.form-control{:name => "term", value: params[:term], :placeholder => "Search term...", :type => "text"}
              %span.input-group-btn
                = submit_tag 'Search', name: nil, class: "btn btn-primary", :onclick => "search()"

#spinner.spinner{:style => "display:none;"}
  %i.fa.fa-spinner.fa-spin{:style => "font-size:80px;"}

%br
%br
#show-list

#my_modal_content

:javascript
  $(function(){
     $('.pagination a').attr('data-remote', 'true')
  });

  function search() {
   $('#spinner').show();
  }

app/views/applicants/search.js.erb
$("#show-list").fadeOut('100');
// $("#show-list").html("<%= escape_javascript(render "list", :locals => {:applicants => @applicants}) %>");
$("#show-list").html("<%= j render "list", applicants: @applicants %>");
$("#show-list").fadeIn('100');
$('.pagination a').attr('data-remote', 'true');
$('#spinner').hide();

app/views/applicants/show.html.haml
.row
  .col-md-3
    %h3 Data pulled from Resume
    %hr
    %br
    = form_tag("#", method: "post") do 
      %p
        %label Name
        = text_field_tag "firstName", "", class: "form-control"
      %p
        %label Email
        = text_field_tag "email", "", class: "form-control"
      %p
        %label Phone
        = text_field_tag "phone", "", class: "form-control"
      %p
        %label State
        = text_field_tag "state", "", class: "form-control"       
      %p
        %label PostalCode
        = text_field_tag "postalCode", "", class: "form-control"
      %p
        %label Skills
        = text_field_tag "primarySkills", "", class: "form-control" 
      %p
        = submit_tag "Save", name: nil, class: "btn btn-primary"
    
  .col-md-9
    %iframe{src: "http://localhost:3000/applicants/5a4dfdda92f5e864ec2f72a8/resume.pdf",  allowfullscreen: "true", width: "100%", height: "500"}

app/views/applicants/view_resume.js.erb
$("#my_modal_content").html("<%= j render "my_modal", resume: @resume %>");
$("#myModal").modal('show');