config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'

  resources :clients
  resources :applicants do
    member do
      get 'view_resume'
      get 'resume'
    end
    collection do
      get "search"
    end
  end
  resources :resumes do
    collection do
      get "search"
    end
  end

  root to: "clients#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_navbar.html.haml
%nav.navbar.navbar-default{:role => "navigation"}
  .row
    .navbar-header
      %button.navbar-toggle{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{:href => root_path} ParamRecruit

      %ul.nav.navbar-nav.navbar-right
        %li
          %a{:href => applicants_path } Applicants
        %li
          %a{:href => search_applicants_path } Search
        %li
          %a{:href =>  search_resumes_path } Resume Search            
        %li
          %a{:href => "#", title: "New Resume", "data-target" => "#myModal", "data-toggle" => "modal"}
            %span.glyphicon.glyphicon-plus

app/views/shared/_new_resume.html.haml
#myModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog
    .modal-content
      = form_tag(resumes_path, method: :post) do
        .modal-header
          %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
          %h4#myModalLabel.modal-title Add New Resume
        .modal-body
          = text_area_tag "content", "", cols: "60", rows: "30" #, :class => 'ckeditor'
        .modal-footer
          %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Close
          = submit_tag "Save", class: "btn btn-primary"