config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'

  resources :clients
  resources :applicants do
    member do
      get 'view_resume'
      get 'resume'
    end
    collection do
      get "search"
    end
  end
  resources :resumes do
    collection do
      get "search"
    end
  end

  root to: "clients#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/client.rb
class Client
  include Mongoid::Document
	include Mongoid::Attributes::Dynamic
  include Mongoid::Timestamps
  
  field :bm_id, type: String
  field :name, type: String
  field :website, type: String
  field :address1, type: String
  field :address2, type: String
  field :municipality, type: String
  field :postalcode, type: String 
  field :discountpct, type: String
  field :discountfee, type: String
  field :stockstymbol, type: String   
  field :info, type: String   
  
  validates :name, :bm_id, presence: true
  validates :name, uniqueness: {scope: :bm_id}
  
  def self.import_bmdata_from_xml
    obj1 = Parsexml.new
    total_count, list = obj1.get_files("public", "client")
    STDOUT.puts "Processing #{total_count} clients"
    list.each_with_index do |item, i|
      STDOUT.print "#{i + 1}...#{item.inspect}...."
        _id = item["iD"].try(:strip)
      _params = item.delete_if {|k,v| k.match(/(id|status|date)/i) }
      _params.merge!(bm_id: _id)
      STDOUT.puts "...Id..#{_id}...#{_params.inspect}"
      c = Client.new(_params)
      if c.save
        STDOUT.puts "Saved"
      else
        STDOUT.puts "Errors: #{c.errors.full_messages.inspect}"
      end
    end
  end
      
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :load_client, only: [:edit, :update, :show, :destroy]
  
  def index
    @clients = Client.all
  end

  def new
    @client = Client.new
  end

  def create
    @client = Client.new(client_params)
    if @client.save
      redirect_to clients_path
    else
      render action: :new
    end
  end

  def edit
    @client = Client.find(params[:id])
  end

  def update
    if @client.update(client_params)
      redirect_to clients_path
    else
      render action: :edit
    end
  end

  def show
  end

  def destroy
    @client.destroy
    redirect_to clients_path
  end
  
  private
  def load_client
    @client = Client.find(params[:id])
  end

  def client_params
    params.require(:client).permit(:name, :website, :address1, :address2, :municipality, :postalcode, 
:discountpct, :discountfee, :stockstymbol, :info)
  end

end

app/helpers/clients_helper.rb
module ClientsHelper

  def colmn_names
    #Client.fields.keys.delete_if {|a| a.match(/(_at|info)/i) }
    %w(bm_id name website)
  end

end

app/views/clients/edit.html.haml
%h1 Clients#edit
%p Find me in app/views/clients/edit.html.haml

app/views/clients/index.html.haml
%h1 Clients#index
%p Find me in app/views/clients/index.html.haml

%table.table.table-hover#clients.display
  %tr
    - colmn_names.each do |colmn|
      %th= colmn
    %th
  - @clients.each do |c|
    %tr
      - colmn_names.each do |colmn|
        %td= c.send(colmn)
      %td
        = link_to "Edit", edit_client_path(c)
        = link_to "Remove", client_path(c), method: :delete, data: { confirm: 'Are you sure?' }

= link_to "New", new_client_path

:javascript
  $(document).ready(function() {
    $('#clients').DataTable({
      "oLanguage": {
        "sLengthMenu": "Show _MENU_ clients",
        "sZeroRecords": "No matching clients found",
        "sInfoEmpty": "Showing 0 to 0 of 0 clients",
        "sInfo": "Showing _START_ to _END_ of _TOTAL_ clients",
        "sInfoFiltered": "(filtered from _MAX_ total clients)"
      }
    });
  } );

app/views/clients/new.html.haml
%h1 Clients#new
%p Find me in app/views/clients/new.html.haml

= form_for @client do |f|
  = f.text_field :name
  = f.submit "Save"

app/views/clients/show.html.haml
%h1 Clients#show
%p Find me in app/views/clients/show.html.haml