config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'

  resources :clients
  resources :applicants do
    member do
      get 'view_resume'
      get 'resume'
    end
    collection do
      get "search"
    end
  end
  resources :resumes do
    collection do
      get "search"
    end
  end

  root to: "clients#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/resume.rb
class Resume
  include Mongoid::Document
	include Mongoid::Attributes::Dynamic
  include Mongoid::Timestamps
  include Mongoid::Search

  field :bm_id, type: String
  field :applicantID, type: String
  field :createDate, type: Time
  field :content, type: String
  field :applicant_id, type: BSON::ObjectId

  # belongs_to :applicant, class_name: "Applicant", foreign_key: "applicant_id"
  validates :bm_id, uniqueness: true

  search_in :content

#  after_create :set_applicant_data
#
#  def set_applicant_data
#    params = CrawlResume.parse(self.content)
#    applicant = Applicant.where(email: params["email"]).first
#    if applicant.present?
#      self.update(:applicant_id => applicant.id)
#    else
#      applicant = Applicant.new(params)
#      if applicant.save(validate: false)
#        self.update(:applicant_id => applicant.id)
#      end
#    end
#    false
#  end


  def self.import_bmdata_from_xml
    obj1 = Parsexml.new
    total_count, list = obj1.get_files("public", "resume")
    STDOUT.puts "Processing #{total_count} resumes"
    list.each_with_index do |item, i|
      _id = item["iD"].try(:strip)
      applicantId = item["applicantID"].try(:strip)
      user = Applicant.where(bm_id: applicantId).first
      STDOUT.print "#{i + 1}...#{applicantId}.......#{item.keys.inspect}..."
      _params = item.delete_if {|k,v| k.match(/(iD|name)/) }
      _params.merge!(bm_id: _id)
      _params.merge!(applicant_id: user.id) if user.present?
      Rails.logger.debug "...333...#{_params.keys.inspect}"
      c = Resume.new(_params)
      if c.save
        #STDOUT.print "Saved"
      else
        STDOUT.puts "Errors: .#{_id}..#{c.errors.full_messages.inspect}"
      end
    end
  end

end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  before_action :load_resume, only: [:edit, :update, :show, :destroy]

  def index
    @resumes = Resume.all
  end

  def search
    if params[:term].present?
      str = params[:match].presence || "all"
      @resumes = Resume.full_text_search("#{params[:term]}", match: str.to_sym).paginate(page: params[:page], per_page: 100)
       #.where(:email => /#{params[:term]}/i)
       respond_to do |format|
          format.js
          format.html
        end
    else
      @resumes = Resume.none
    end
  end

  def new
    @resume = Resume.new
  end

  def create
    @resume = Resume.new(resume_params)
    if @resume.save(validate: false)
      redirect_to resume_path(@resume)
    else
      Rails.logger.debug "\n\n...ERR..#{@resume.errors.inspect}...\n"
      redirect_to search_applicants_path
      #render action: :new
    end
  end

  def edit
    @resume = Resume.find(params[:id])
  end

  def update
    if @resume.update(resume_params)
      redirect_to resumes_path
    else
      render action: :edit
    end
  end

  def show
    @details = CrawlResume.parse(@resume.content)
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "show"   # Excluding ".pdf" extension.
      end
    end
  end

  def destroy
    @resume.destroy
    redirect_to resumes_path
  end

  private
  def load_resume
    @resume = Resume.find(params[:id])
  end

  def resume_params
    params.permit(:content, :applicant_id)
  end

end

app/views/resumes/_list.html.haml
= page_entries_info @resumes
%br
%table.table.table-hover
  %thead
    %tr
      %th bm_id
      %th Resume
      %th
  %tbody
    - @resumes.each do |r|
      %tr
        %td= r.bm_id
        %td= link_to "View Resume", resume_path(r, "pdf"), :target => "_blank"
        %td
          = link_to "Edit", edit_resume_path(r)
          &nbsp;|&nbsp;
          = link_to "Remove", resume_path(r), method: :delete, data: { confirm: 'Are you sure?' }

= will_paginate @resumes

app/views/resumes/search.html.haml
.panel{:style => "margin-top:36px;margin-bottom:45px;"}
  .panel-heading{:style => "text-align:center;margin: -1px;color:white;background-color:#4B515D !important;"}
    %h4 Search Resumes


.container
  .row
    .col-xs-8.col-xs-offset-2
      = form_tag(search_resumes_path , method: :get, remote: true) do
        .input-group
          .input-group-btn.search-panel
            %button.btn.btn-primary.dropdown-toggle{"data-toggle" => "dropdown", :type => "button"}
              %span#search_concept Filter by
              %span.caret
            %ul.dropdown-menu{:role => "menu"}
              %li
                %a{:href => "#all"} AND
              %li
                %a{:href => "#any"} OR
          %input#match{:name => "match", :type => "hidden", :value => "all"}
            %input.form-control{:name => "term", value: params[:term], :placeholder => "Search term...", :type => "text"}
              %span.input-group-btn
                = submit_tag 'Search', name: nil, class: "btn btn-primary", :onclick => "search()"

#spinner.spinner{:style => "display:none;"}
  %i.fa.fa-spinner.fa-spin{:style => "font-size:80px;"}

%br
%br
#show-resume-list

#my_modal_content

:javascript
  $(function(){
     $('.pagination a').attr('data-remote', 'true')
  });

  function search() {
   $('#spinner').show();
  }

app/views/resumes/search.js.erb
$("#show-resume-list").fadeOut('100');
// $("#show-list").html("<%= escape_javascript(render "list", :locals => {:applicants => @applicants}) %>");
$("#show-resume-list").html("<%= j render "list", resumes: @resumes %>");
$("#show-resume-list").fadeIn('100');
$('.pagination a').attr('data-remote', 'true');
$('#spinner').hide();

app/views/resumes/show.html.haml
.row
  .col-md-3
    %h3 Data pulled from Resume
    %hr
    %br
    = form_tag(applicants_path, method: "post") do 
      = hidden_field_tag "resume_id", @resume.id
      %p
        %label Name
        = text_field_tag "firstName", @details["firstName"], class: "form-control"
      %p
        %label Email
        = text_field_tag "email", @details["email"], class: "form-control"
      %p
        %label Phone
        = text_field_tag "phone", @details["phone"], class: "form-control"
      %p
        %label State
        = text_field_tag "state", @details["state"], class: "form-control"       
      %p
        %label PostalCode
        = text_field_tag "postalCode", @details["postalCode"], class: "form-control"
      %p
        %label Skills
        = text_area_tag "primarySkills", @details["primarySkills"], rows: 6, class: "form-control" 
      %p
        = submit_tag "Save", name: nil, class: "btn btn-primary"
    
  .col-md-9
    %iframe{src: "#{root_url}/resumes/#{@resume.id.to_s}.pdf",  allowfullscreen: "true", width: "100%", height: "500"}

app/views/resumes/show.pdf.erb
<div style="white-space: pre-wrap;">
  <% if @resume.present? %>
    <%= @resume.content.html_safe %>
  <% else %>  
    "Resume not found!"
  <% end %>
</div>